# Generated by Django 6.0.5 on 2026-06-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_componentregistry_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentregistry",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
