# Generated by Django 6.0.5 on 2026-06-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_componentregistry_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="category",
        ),
        migrations.RemoveField(
            model_name="componentfile",
            name="component",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Component",
        ),
        migrations.DeleteModel(
            name="ComponentFile",
        ),
        migrations.DeleteModel(
            name="ComponentRegistry",
        ),
    ]
