# Generated by Django 6.0.5 on 2026-06-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("dependencies", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Component Registries",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="component",
            name="accessibility",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="component",
            name="dependencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="component",
            name="interaction_strategy",
            field=models.CharField(
                choices=[
                    ("static", "Static"),
                    ("htmx", "HTMX"),
                    ("alpine", "Alpine.js"),
                    ("vanilla", "Vanilla JS"),
                ],
                default="static",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="version",
            field=models.CharField(default="1.0.0", max_length=20),
        ),
        migrations.AlterField(
            model_name="component",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ComponentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.componentregistry",
                    ),
                ),
            ],
        ),
    ]
